### ISSUE TITLE
Error Message in Excel

### ISSUE THREAD

**Issue by TanjaWeber** [maxim-uvarov/PQGoogleAnalytics#1]
Sorry, but I can't find any other form of communication:

I'm having a little trouble running the query. When I hit "refresh_token" I get an error message. "Query #authorisation_token' (step removed other  Columns') references other queries or steps and so may not directly access a data source." In Power Query the step 'GetJson' already hits an error. Any ideas?

**Comment by maxim-uvarov** [comment]
Hello Tanya:)
This is the right place to ask questions:)

Have you turned on fast combine? (Ignore the privacy levels option)?

![](https://www.evernote.com/l/AAlg-MU3CLJId44g2Gcn9I77xjMjmmVdnBIB/image.png)

![](https://www.evernote.com/l/AAmly43tR6RKaYdxOdcCrpN84upTvH5TEIEB/image.png)

**Comment by TanjaWeber** [comment]
Hi Maxim,
thanks for the quick reply.
Switched on Fast Combine, but am still getting an error message (see attachment).
Power Query Step Get Json: “DataSource.Error: Web.Contents failed to get contents from 'https://accounts.google.com/o/oauth2/token' (400): Bad Request
Details:
    https://accounts.google.com/o/oauth2/token”

**Comment by maxim-uvarov** [comment]
It can be if you are trying to get refresh token second time. It can be
retrieved only once.

Please, follow the steps as it descibed in manual:
1. Use link to get auth token
2. Copy and paste auth token
3. Push button to get refresh token

When it is retrieved you dont need to refresh it, so you can use reports
again and again:)

Let me know if doesnt work

Max

On Wednesday, May 6, 2015, TanjaWeber notifications@github.com wrote:

> Hi Maxim,
> thanks for the quick reply.
> Switched on Fast Combine, but am still getting an error message (see
> attachment).
> Power Query Step Get Json: “DataSource.Error: Web.Contents failed to get
> contents from 'https://accounts.google.com/o/oauth2/token' (400): Bad
> Request
> Details:
> https://accounts.google.com/o/oauth2/token”
> 
> From: Maxim Uvarov [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Tuesday, May 5, 2015 7:27 PM
> To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> Cc: Tanja Weber
> Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in Excel
> (#1)
> 
> Hello Tanya:)
> This is the right place to ask questions:)
> 
> Have you turned on fast combine? (Ignore the privacy levels option)?
> 
> [
> https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67
> ]<
> https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67>
> 
> [
> https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67
> ]<
> https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67>
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99150650>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99380646
> .

## 

+7.925.8024003

Sent from microwave oven. Supposed to contain typos.
o_O

**Comment by TanjaWeber** [comment]
Sorry Max, that’s what I’ve been doing, but the first refresh doesn’t work.That specific query runs an error.

Any other ideas?
By the way, the url has a dot at the end, and therefore I always have to remove that first.

**Comment by maxim-uvarov** [comment]
Well, Im out of pc temporarily
When Im back I'll check all the steps again.

There is already pasted token in distrib with access to marketing-wiki.ru
google analytics

Can you try please to get report with it?

Max

On Wednesday, May 6, 2015, TanjaWeber notifications@github.com wrote:

> Sorry Max, that’s what I’ve been doing, but the first refresh doesn’t
> work.That specific query runs an error.
> 
> Any other ideas?
> By the way, the url has a dot at the end, and therefore I always have to
> remove that first.
> 
> From: Maxim Uvarov [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Wednesday, May 6, 2015 11:31 AM
> To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> Cc: Tanja Weber
> Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in Excel
> (#1)
> 
> It can be if you are trying to get refresh token second time. It can be
> retrieved only once.
> 
> Please, follow the steps as it descibed in manual:
> 1. Use link to get auth token
> 2. Copy and paste auth token
> 3. Push button to get refresh token
> 
> When it is retrieved you dont need to refresh it, so you can use reports
> again and again:)
> 
> Let me know if doesnt work
> 
> Max
> 
> On Wednesday, May 6, 2015, TanjaWeber <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
> 
> > Hi Maxim,
> > thanks for the quick reply.
> > Switched on Fast Combine, but am still getting an error message (see
> > attachment).
> > Power Query Step Get Json: “DataSource.Error: Web.Contents failed to get
> > contents from 'https://accounts.google.com/o/oauth2/token' (400): Bad
> > Request
> > Details:
> > https://accounts.google.com/o/oauth2/token”
> > 
> > From: Maxim Uvarov [mailto:notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');><mailto:
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');%3e>]
> > Sent: Tuesday, May 5, 2015 7:27 PM
> > To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> > Cc: Tanja Weber
> > Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in
> > Excel
> > (#1)
> > 
> > Hello Tanya:)
> > This is the right place to ask questions:)
> > 
> > Have you turned on fast combine? (Ignore the privacy levels option)?
> > 
> > [
> > 
> > https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67
> > ]<
> > 
> > https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67>
> > 
> > [
> > 
> > https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67
> > ]<
> > 
> > https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67>
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99150650>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99380646>
> > 
> > .
> 
> ## 
> 
> +7.925.8024003
> 
> Sent from microwave oven. Supposed to contain typos.
> o_O
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99397027>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99463484
> .

## 

+7.925.8024003

Sent from microwave oven. Supposed to contain typos.
o_O

**Comment by TanjaWeber** [comment]
Nope, same error.
Sorry ☹

Probably some other setting that isn’t set the correct way…

**Comment by maxim-uvarov** [comment]
Can you tell me pls what is your setup?
Windows/excel/power query version

On Thursday, May 7, 2015, TanjaWeber notifications@github.com wrote:

> Nope, same error.
> Sorry ☹
> 
> Probably some other setting that isn’t set the correct way…
> 
> From: Maxim Uvarov [mailto:notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>]
> Sent: Wednesday, May 6, 2015 7:16 PM
> To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> Cc: Tanja Weber
> Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in Excel
> (#1)
> 
> Well, Im out of pc temporarily
> When Im back I'll check all the steps again.
> 
> There is already pasted token in distrib with access to marketing-wiki.ru
> google analytics
> 
> Can you try please to get report with it?
> 
> Max
> 
> On Wednesday, May 6, 2015, TanjaWeber <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>> wrote:
> 
> > Sorry Max, that’s what I’ve been doing, but the first refresh doesn’t
> > work.That specific query runs an error.
> > 
> > Any other ideas?
> > By the way, the url has a dot at the end, and therefore I always have to
> > remove that first.
> > 
> > From: Maxim Uvarov [mailto:notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');><mailto:
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');%3e>]
> > Sent: Wednesday, May 6, 2015 11:31 AM
> > To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> > Cc: Tanja Weber
> > Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in
> > Excel
> > (#1)
> > 
> > It can be if you are trying to get refresh token second time. It can be
> > retrieved only once.
> > 
> > Please, follow the steps as it descibed in manual:
> > 1. Use link to get auth token
> > 2. Copy and paste auth token
> > 3. Push button to get refresh token
> > 
> > When it is retrieved you dont need to refresh it, so you can use reports
> > again and again:)
> > 
> > Let me know if doesnt work
> > 
> > Max
> > 
> > On Wednesday, May 6, 2015, TanjaWeber <notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > <mailto:notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>%0b>>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');><mailto:
> > <mailto:%0b>> notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');><mailto:
> > notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>> wrote:
> > 
> > > Hi Maxim,
> > > thanks for the quick reply.
> > > Switched on Fast Combine, but am still getting an error message (see
> > > attachment).
> > > Power Query Step Get Json: “DataSource.Error: Web.Contents failed to
> > > get
> > > contents from 'https://accounts.google.com/o/oauth2/token' (400): Bad
> > > Request
> > > Details:
> > > https://accounts.google.com/o/oauth2/token”
> > > 
> > > From: Maxim Uvarov [mailto:notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>');><mailto:
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>
> > > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > ');>');%3e><mailto:notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > ');%3e%0b%3e%20%3e%20%3cjavascript:_e(%7B%7D,'cvml','
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');%3e');%
> > > 3e%3cmailto:%0b%3e%20notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','3e%253cmailto:%250b%253e%2520notifications@github.com');>
> > > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > ');%3e%0b%3e%20%0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','
> > > notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > %0b%3e%20%3cjavascript:_e(%7B%7D,'cvml','notifications@github.com
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');%3e');%3e%3e>]
> > > 
> > > Sent: Tuesday, May 5, 2015 7:27 PM
> > > To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> > > Cc: Tanja Weber
> > > Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in
> > > Excel
> > > (#1)
> > > 
> > > Hello Tanya:)
> > > This is the right place to ask questions:)
> > > 
> > > Have you turned on fast combine? (Ignore the privacy levels option)?
> > > 
> > > [
> > 
> > https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67
> > 
> > > ]<
> > 
> > https://camo.githubusercontent.com/cc6300976b544848b05ad639782147342508e3c3/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416c672d4d5533434c4a49643434673247636e39493737786a4d6a6d6d56646e4249422f696d6167652e706e67>
> > 
> > > [
> > 
> > https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67
> > 
> > > ]<
> > 
> > https://camo.githubusercontent.com/a8d35f6bc5833025a3ce2d3bd1b4826e75e76a92/68747470733a2f2f7777772e657665726e6f74652e636f6d2f6c2f41416d6c793433745236524b615964784f64634372704e383475705476483554454945422f696d6167652e706e67>
> > 
> > > —
> > > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99150650>.
> > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99380646>
> > 
> > > .
> > 
> > ## 
> > 
> > +7.925.8024003
> > 
> > Sent from microwave oven. Supposed to contain typos.
> > o_O
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > 
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99397027>.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99463484>
> > 
> > .
> 
> ## 
> 
> +7.925.8024003
> 
> Sent from microwave oven. Supposed to contain typos.
> o_O
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99541663>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-99762646
> .

## 

+7.925.8024003

Sent from microwave oven. Supposed to contain typos.
o_O

**Comment by TanjaWeber** [comment]
Gladly ;)

Windows 8.1
Excel 2013 (15.0.4711.1000) 64-bit
Power Query: Version: 2.21.3974.242

**Comment by maxim-uvarov** [comment]
I have almost the same setup. 
I've just updated power query to [latest version](https://support.office.com/en-us/article/Whats-new-in-Power-Query-936b2fca-4168-41ad-bbbd-7b83856b6776?ui=en-US&rs=en-US&ad=US&Ocid=Excel_Social_TWITTER_msexcel_20150504_176341939) and made a new build of excel file with it. 

To try it please do next:
1. download it from [here](https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/releases/tag/1.01)
2. [Enable fast combine](https://www.evernote.com/l/AAmdYbEWUj9OWY-HNYkgfZiUGfg78SOzJYMB/image.png)
3. [Try to get report with default token](https://www.evernote.com/l/AAkJIsvSBj1Ci7x9Ena5qqcszulnFm6d8ssB/image.png)

And please let me know about result.

**Comment by TanjaWeber** [comment]
Hi Max,

sorry, for the delayed reply.

That works (more or less). It first results in an error, but when I jump into the query, I need to edit the Credentials from
https://www.googleapis.com to https://www.googleapis.com/analytics/v3/data/. And then the query “getData” produces “Results”.

**Comment by maxim-uvarov** [comment]
I'm glad:)
Can you try to get reports for your accounts too?

**Comment by TanjaWeber** [comment]
Nope, not yet.

I think there is a problem with the Data Source Credentials. Could it be that only Users with admin rights in Google Analytics get access?

Or could we maybe take a look together via skype?

**Comment by maxim-uvarov** [comment]
You don't need to be admin to get data via api.

Add me on skype: maxim.uvaroff, and we would try together

Max

On 8 May 2015 at 19:16, TanjaWeber notifications@github.com wrote:

> Nope, not yet.
> 
> I think there is a problem with the Data Source Credentials. Could it be
> that only Users with admin rights in Google Analytics get access?
> 
> Or could we maybe take a look together via skype?
> 
> From: Maxim Uvarov [mailto:notifications@github.com]
> Sent: Friday, May 8, 2015 6:10 PM
> To: 40-02/GoogleAnalyticsViaPowerQueryForExcel
> Cc: Tanja Weber
> Subject: Re: [GoogleAnalyticsViaPowerQueryForExcel] Error Message in Excel
> (#1)
> 
> I'm glad:)
> Can you try to get reports for your accounts too?
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-100283145>.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40-02/GoogleAnalyticsViaPowerQueryForExcel/issues/1#issuecomment-100284370
> .

## 

Cheers,
Maxim Uvarov
+7.925.8024003

**Comment by maxim-uvarov** [comment]
It seems like we'd worked this out:)
