### ISSUE TITLE
Problem with refresh_token

### ISSUE THREAD

**Issue by gyudin** [maxim-uvarov/PQGoogleAnalytics#2]
Hi, Maxim!
For some reasons i get errors after i hit "Get refresh_token" button. I've tried to turn off privacy control for data, but now i'm getting another error. 
[Datasource.Error] Web.Contents failed to get contents from 'https://accounts.google.com/o/oauth2/token' (400): Bad request

Any particular Data Source settings are required?

Btw. first hyperlink, that grants access is broken.

**Comment by maxim-uvarov** [comment]
Hi there:)
This problem appears usually when you are trying to get refresh token second time. 
The token that you get going by link in file can be used only once. 
Please try to get a new one. 

I've uploaded the new version of file.  
You can find it here. 
https://github.com/40-02/PQGoogleAnalytics/releases/tag/2.0

Let me know if you have any problems.

**Comment by gyudin** [comment]
Thanks for your answer, it seems solved it.
Now i'm getting "Run time error '9': Subscript out of range" when i'm trying to run report on "Report Config Table".

**Comment by maxim-uvarov** [comment]
it seems like there is a problem with macros. I'll repair it on weekend :(
Try use refresh in Power Query
![image](https://cloud.githubusercontent.com/assets/4896754/9785737/2c82fb4a-57bd-11e5-811b-49f2ecf49688.png)

**Comment by gyudin** [comment]
Вроде пробовал всё, что только можно рефрешить, не помогает :)
![screenshot_3](https://cloud.githubusercontent.com/assets/4328128/10367273/206d0892-6dd8-11e5-8418-e4619196bada.png)

**Comment by maxim-uvarov** [comment]
Нашли ошибку
Сегодня постараемся релиз опубликовать

On Thu, Oct 8, 2015 at 4:18 PM, Georgi Yudin notifications@github.com
wrote:

> Вроде пробовал всё, что только можно рефрешить, не помогает :)
> [image: screenshot_3]
> https://cloud.githubusercontent.com/assets/4328128/10367273/206d0892-6dd8-11e5-8418-e4619196bada.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/40-02/PQGoogleAnalytics/issues/2#issuecomment-146542177
> .

## 

Cheers,
Maxim Uvarov
+7.925.8024003

**Comment by yiah** [comment]
Hi

I have problems with the privacy levels. Tried on different computers and I get the same problem. I' m using Excel 2013 64bit on Win.

![image](https://cloud.githubusercontent.com/assets/376558/10498943/cd6c551c-72cd-11e5-9de6-f757f39a1620.png)

**Comment by bobwe** [comment]
I have the same issue as Yiah

**Comment by maxim-uvarov** [comment]
@yiah @bobwe please, make sure that you have enabled the option "ignore the privacy levels and potentially improve performance"

I made a short video for 2016:
https://youtu.be/luMfcoL2a4I
