### ISSUE TITLE
Latest version is missing a query

### ISSUE THREAD

**Issue by Grumelo** [maxim-uvarov/PQGoogleAnalytics#3]
In the latest version of your excel file the query getdata (5) is missing and some related queries too.
Refreshing the Data query wont work

**Comment by maxim-uvarov** [comment]
sorry, 
Hope to fix and optimise many things in this script soon. 
There is going to be a new build.

**Comment by timharrison2015** [comment]
Hi, i'm getting this error in excel when I hit the "Run report and go on results page" (authentication seemed to have worked though)

![error](https://cloud.githubusercontent.com/assets/11520928/15076538/1fedbe14-13a2-11e6-9809-015c9e0c8ad5.PNG)

**Comment by maxim-uvarov** [comment]
The new release:
https://github.com/40-02/PQGoogleAnalytics/releases/tag/2.10
