### ISSUE TITLE
Run time error

### ISSUE THREAD

**Issue by timharrison2015** [maxim-uvarov/PQGoogleAnalytics#4]
Hi, i'm getting this error in excel when I hit the "Run report and go on results page" (authentication seemed to have worked though)

![error](https://cloud.githubusercontent.com/assets/11520928/15076538/1fedbe14-13a2-11e6-9809-015c9e0c8ad5.PNG)

**Comment by maxim-uvarov** [comment]
Please, check the new release:
https://github.com/40-02/PQGoogleAnalytics/releases/tag/2.10
