### ISSUE TITLE
Как поправить  ошибку "DataSource.Error: Web.Contents не удалось получить содержимое"? 

### ISSUE THREAD

**Issue by EvgeniyaKorotkih** [maxim-uvarov/PQGoogleAnalytics#5]
Добрый день.
При выполнении запроса к Google Analytics в Power Bi появляется вот такая ошибка:
В запросе "PQGA" произошла ошибка. DataSource.Error: Web.Contents не удалось получить содержимое из "https://www.googleapis.com/analytics/v3/data/ga?ids=109075275&start-date=2017-06-01&end-date=2017-06-22&metrics=ga%3AadClicks&access_token=тут токен&max-results=10000" (400): Bad Request
Подробные сведения:
    DataSourceKind=Web
    DataSourcePath=https://www.googleapis.com/analytics/v3/data/ga
    Url=https://www.googleapis.com/analytics/v3/data/ga?ids=109075275&amp;start-date=2017-06-01&amp;end-date=2017-06-22&amp;metrics=ga%3AadClicks&amp;access_token=тут токен&amp;max-results=10000

Подскажите, пожалуйста, как исправить?

**Comment by maxim-uvarov** [comment]
Евгения, извините, пропустил ваш вопрос. 

Есть вероятность, что мудреная процедура аутентификации была пройдена не полностью. Если вдруг актуально - открывайте issue вновь.
