### ISSUE TITLE
Access to the resource is forbidden

### ISSUE THREAD

**Issue by Sashazhestkov** [maxim-uvarov/PQGoogleAnalytics#6]
After click "Close&Apply" have an error: 

<img width="1440" alt="2017-11-13 20 21 26" src="https://user-images.githubusercontent.com/13706135/32741504-8261425c-c8b7-11e7-9b63-e00af2da0cdb.png">

**Comment by maxim-uvarov** [comment]
Sorry for long answer. It seems like authorization process wasn't completed successfully.
