### ISSUE TITLE
Setup for PowerBI.com refresh

### ISSUE THREAD

**Issue by Calvinferns** [maxim-uvarov/PQGoogleAnalytics#7]
Hi, thanks for the great project.  

Has anyone had success scheduling refresh from the Power BI portal? I am struggling and dont know what data source i need to add into the data gateway, adding https://googleapis.com/analytics/v3/data/ga as a datasource doesnt seem to be allowed as it doesnt resolve to a proper URL until the PQ code is run.  

Any tips?
![image](https://user-images.githubusercontent.com/36191458/35855235-86ea135c-0b2a-11e8-9fad-28a347d696fc.png)

Calvin

**Comment by maxim-uvarov** [comment]
Hello, Calvin!

Sorry for the delayed answer. With current authorization process of google analytics and restrictions of Power BI service, there is no way to establish automatic refresh in the service. I was thinking about it a lot, but I couldn't find a solution. 

Custom Power BI connectors might resolve this issue, but we don't know when they become available.
