### ISSUE TITLE
Ошибка текстового значение в поле endDateVar

### ISSUE THREAD

**Issue by ILuckyManI** [maxim-uvarov/PQGoogleAnalytics#9]
Максим, здравствуйте.
В функции PQGA при вводе значения "yesterday" в поле endDateVar выдаёт ошибку "Enter a Date value". 
Как в данной функции можно ограничить время сбора данных по вчерашнее число?
![pqga](https://user-images.githubusercontent.com/69075479/90955240-8b2cb380-e484-11ea-9f3a-2ccaee0868ca.png)

P.S. 
Спасибо большое за ваши труды.

**Comment by maxim-uvarov** [comment]
@ILuckyManI, здравствуйте! 
Извините за задержку с ответом. Почему то не получил уведомления. 
В текущей версии коннектора из данного репозитория в поле дата можно вписать только данные в формате дата. 
Слова yesterday, 3daysAgo не поддерживаются. 

Но зато вы можете попробовать версию коннектора Александра Морина:
https://github.com/morinad/PQGoogleAnalytics

В ней можно использовать фразы типа yesterday. Вот видео про коннектор https://www.youtube.com/watch?v=svTUuNLEZ0o&feature=emb_title

Либо, в моем коннекторе вы можете прописать конструкцию =Date.AddDays(DateTime.LocalNow(),-1) - 
такая конструкция будет автоматически подставлять вчерашнюю дату.
